apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "track-day-legends.fullname" . }}-config
  labels:
    {{- include "track-day-legends.labels" . | nindent 4 }}
{{- if .Values.env }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
