replicaCount: 1

image:
  tag: "dev-1.0.0"
  pullPolicy: IfNotPresent

env:
  SPRING_PROFILES_ACTIVE: "dev"
  JAVA_TOOL_OPTIONS: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

ingress:
  enabled: false

autoscaling:
  enabled: false

secret:
  create: false
  existingSecret: ""
